### PR TITLE
add .gpkg test file

### PR DESCRIPTION
**Pull request by jfb-h**
This is the lowest resolution file from: https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/grids

### CODE REVIEW

**Comment by tecosaur** [comment]
Thanks! :grinning:

**Comment by tecosaur** [comment]
Oh, what's the licence for this BTW?

**Comment by jfb-h** [comment]
This is the Eurostat license info: https://ec.europa.eu/eurostat/about-us/policies/copyright 
So it should be good to go if the source is mentioned somewhere.

**Comment by tecosaur** [comment]
Ta, I'll add a data licences section to the readme

**Pull request merged**
